### ISSUE TITLE
Not listed in the Quarkus extension catalog

### ISSUE THREAD

**Issue by Mai-Lapyst** [quarkiverse/quarkus-morphia#15]
Hi, ive notived that this extension is not listed in the Quarkus extension catalog; neither on code.quarkus.io nor with the quarkus cli tools. It would be handy if this extension somehow can get listed so people who wish to use an full-flavored ODB for mongoDB have the ability to do so.

**Comment by evanchooly** [comment]
It wasn't usable then.  It's almost usable now (I was working on other things).  It should be available soon to experiment with.

**Comment by evanchooly** [comment]
available now as a preview
