### ISSUE TITLE
Add critter tests

### ISSUE THREAD

**Issue by evanchooly** [quarkiverse/quarkus-morphia#27]

**Comment by melloware** [comment]
Have you been able to get this to work?  I am trying to use your extension in my extension but its complaining about missing dependencies in your `runtime` lib?

**Comment by evanchooly** [comment]
I actually haven't really looked at this much as i've been off working on other things but if it's an active blocker for you i'll definitely give it some time.  I'd added this issue mostly as a bookmark so I wouldn't forget it and now it seems it's time to deal with it.

**Comment by melloware** [comment]
I just posted here because I didn't want to open a new issue but I was trying to use your module and it was saying it was missing dependencies. I will post later what the full error is.

**Comment by evanchooly** [comment]
Curious.  I did just noticed that critter needs a new version to support 2.3.0 so i'll take care of that this weekend.

**Comment by evanchooly** [comment]
merged critter support and tests
