### ISSUE TITLE
Quarkus 3 compatibility

### ISSUE THREAD

**Issue by bonneval** [quarkiverse/quarkus-morphia#61]
Hello,

the quarkus-morphia extension is blocking us to migrate to Quarkus 3 since it is not yet compatible.

Preparation as been done as far as I can tell with the commit [bump to quarkus 3.0.1.Final ](https://github.com/quarkiverse/quarkus-morphia/commit/869dfd879ff450361635f7fc7c1e5bcf72525a58)

I don`t want to be rude but are you planing to release a version compatible with Quarkus 3 soon?

Thanks a lot!

**Comment by evanchooly** [comment]
I apologize.  I missed this notification (did one even get sent?) and I'll push 0.5.0 that just passed with 3.5.0.

**Comment by evanchooly** [comment]
0.5.0 was just pushed
